fixed version fetch

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -52,6 +52,7 @@ else
 fi
 
 # Make binaries available
+export LD_LIBRARY_PATH="${CLAMAV_CACHE}/usr/local/lib64:$LD_LIBRARY_PATH"
 export PATH="${CLAMAV_CACHE}/usr/local/bin:${CLAMAV_CACHE}/usr/local/sbin:$PATH"
 
 echo "Verifying ClamAV installation"
@@ -74,5 +75,17 @@ cp -r "$CLAMAV_CACHE" "$CLAMAV_BUILD"
 
 rm -rf "$DB_BUILD"
 cp -r "$DB_CACHE" "$DB_BUILD"
+
+echo "-----> Verifying ClamAV installation in slug"
+
+export LD_LIBRARY_PATH="${CLAMAV_BUILD}/usr/local/lib64:$LD_LIBRARY_PATH"
+export PATH="${CLAMAV_BUILD}/usr/local/bin:${CLAMAV_BUILD}/usr/local/sbin:$PATH"
+
+echo "Verifying ClamAV installation"
+
+if ! clamscan --version; then
+  echo "ERROR: ClamAV failed to install correctly"
+  exit 1
+fi
 
 echo "-----> ClamAV setup complete"
